-- --------------------------------------------------------
--
-- Purpose: Defines the database schema for the Event Reminder Application.
-- This script is designed for a MySQL database and includes tables for
-- users, events, and AI-pending events, establishing clear relationships
-- and constraints.
--
-- --------------------------------------------------------

--
-- Database: `event_reminder`
--
CREATE DATABASE IF NOT EXISTS `event_reminder` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `event_reminder`;

-- --------------------------------------------------------

--
-- Table structure for table `users`
--
-- Purpose: Stores user account information, including credentials and roles.
-- The `role` column distinguishes between standard 'user' and 'admin'.
--

CREATE TABLE `users` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL UNIQUE,
  `password` VARCHAR(255) NOT NULL,
  `role` ENUM('user', 'admin') NOT NULL DEFAULT 'user',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

--
-- Dumping data for table `users`
--
-- Note: Passwords are hashed using PHP's password_hash() function.
-- The plain text passwords are 'password' for the test user and 'adminpassword' for the admin.
--

INSERT INTO `users` (`id`, `name`, `email`, `password`, `role`, `created_at`) VALUES
(1, 'Admin User', 'admin@example.com', '$2y$10$H.p6.Q/N7aJjPp.W/T6dZ.p8x.wXh3.wE4i.k6n.wUe/g3C.f2.hG', 'admin', NOW()),
(2, 'Test User', 'user@example.com', '$2y$10$mPLd32/v4T75xFC2O0aMFeKz4S5v.OUc/C9x0D.pLz.p1C/j5.f7m', 'user', NOW());

-- --------------------------------------------------------

--
-- Table structure for table `events`
--
-- Purpose: Stores all personal and global events.
-- A NULL `user_id` indicates a 'global' event created by an admin.
-- Reminder flags (`reminder1_sent`, `reminder2_sent`) track email notifications.
--

CREATE TABLE `events` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `user_id` INT NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT,
  `event_date` DATETIME NOT NULL,
  `reminder1_date` DATETIME NOT NULL,
  `reminder2_date` DATETIME NOT NULL,
  `reminder1_sent` BOOLEAN DEFAULT FALSE,
  `reminder2_sent` BOOLEAN DEFAULT FALSE,
  `is_global` BOOLEAN DEFAULT FALSE,
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`user_id`) REFERENCES `users`(`id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


-- --------------------------------------------------------

--
-- Table structure for table `ai_pending_events`
--
-- Purpose: Acts as a staging area for events generated by the AI PDF parser.
-- These events are not visible to users until an admin reviews and approves them,
-- at which point they are moved to the main `events` table.
--

CREATE TABLE `ai_pending_events` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT,
  `event_date` DATETIME NOT NULL,
  `status` ENUM('pending', 'approved', 'rejected') NOT NULL DEFAULT 'pending',
  `source_file` VARCHAR(255) NOT NULL,
  `extracted_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

COMMIT;
